[options.entry_points]
python_components =
    # register Python components
    roboter_tetris::RobotiqGripperComponent = roboter_tetris.robotiq_gripper:RobotiqGripperComponent
    roboter_tetris::TrueSignal = roboter_tetris.true_signal:TrueSignal
    roboter_tetris::ToggleSignal = roboter_tetris.toggle_signal:ToggleSignal
    roboter_tetris::BaseCam = roboter_tetris.base_cam:BaseCam
    roboter_tetris::RobotCam = roboter_tetris.robot_cam:RobotCam
    roboter_tetris::RobotCam2 = roboter_tetris.robot_cam_2:RobotCam2
    roboter_tetris::BoardDetection = roboter_tetris.Calibration.board_detection:BoardDetection
    roboter_tetris::MoveToPoseTest = roboter_tetris.move_to_pose_test:MoveToPoseTest
