[options.entry_points]
python_components =
    # register Python components
    roboter_tetris::RobotiqGripperComponent = roboter_tetris.robotiq_gripper:RobotiqGripperComponent
    roboter_tetris::TrueSignal = roboter_tetris.true_signal:TrueSignal
    roboter_tetris::ToggleSignal = roboter_tetris.toggle_signal:ToggleSignal
    roboter_tetris::BaseCam = roboter_tetris.base_cam:BaseCam